name: .NET 8 CI Test Pipeline

on:
  push:
    branches: [ "main" ]     # chạy khi push lên nhánh main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout code từ repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Setup .NET 8 SDK
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3️⃣ Restore các package NuGet
    - name: Restore dependencies
      run: dotnet restore

    # 4️⃣ Build project
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # 5️⃣ Run test (nếu có test project)
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # 6️⃣ Publish output
    - name: Publish app
      run: dotnet publish -c Release -o ./publish

    # 7️⃣ Deploy đến server (copy file lên)
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        source: "./publish/*"
        target: "/var/www/TestCI"

    # 8️⃣ SSH vào server và chạy app
    - name: Run app on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          pkill dotnet
          mkdir -p /var/www/TestCI
          cd /var/www/TestCI/publish/
          nohup dotnet TestCI.dll --urls "http://0.0.0.0:5000" > app.log 2>&1 &
